"""add market_data models

Revision ID: 2438e4b862c4
Revises: 23189c7092ff
Create Date: 2026-05-31 19:24:50.440332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2438e4b862c4'
down_revision: Union[str, Sequence[str], None] = '23189c7092ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_instrument',
    sa.Column('provider', sa.String(length=20), nullable=False, comment='数据供应商'),
    sa.Column('symbol', sa.String(length=64), nullable=False, comment='对外暴露的规范代码'),
    sa.Column('normalized_symbol', sa.String(length=64), nullable=False, comment='按服务层规则归一化后的 symbol'),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False, comment='供应商原始或主标的代码'),
    sa.Column('normalized_provider_symbol', sa.String(length=64), nullable=False, comment='按服务层规则归一化后的 provider symbol'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='标的名称'),
    sa.Column('display_label', sa.String(length=255), nullable=True, comment='前端展示标签'),
    sa.Column('exchange', sa.String(length=64), nullable=True, comment='交易所'),
    sa.Column('mic_code', sa.String(length=32), nullable=True, comment='MIC 代码'),
    sa.Column('market', sa.String(length=64), nullable=True, comment='市场分类'),
    sa.Column('asset_type', sa.String(length=64), nullable=True, comment='资产类型'),
    sa.Column('country', sa.String(length=64), nullable=True, comment='国家或地区'),
    sa.Column('currency', sa.String(length=16), nullable=True, comment='计价货币'),
    sa.Column('exchange_timezone', sa.String(length=64), nullable=True, comment='交易所时区'),
    sa.Column('provider_plan', sa.String(length=64), nullable=True, comment='供应商可用性或套餐字段'),
    sa.Column('sort_weight', sa.Integer(), nullable=False, comment='搜索排序权重，越小越靠前'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('is_searchable', sa.Boolean(), nullable=False, comment='是否参与搜索'),
    sa.Column('is_hot', sa.Boolean(), nullable=False, comment='是否热池标的'),
    sa.Column('supports_history', sa.Boolean(), nullable=False, comment='是否支持历史 K 线'),
    sa.Column('supports_quote', sa.Boolean(), nullable=False, comment='是否支持报价'),
    sa.Column('source_payload', sa.JSON(), nullable=True, comment='最近一次同步的原始或归一化主数据负载'),
    sa.Column('metadata_synced_at', sa.DateTime(timezone=True), nullable=True, comment='主数据最近同步时间'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次在供应商返回中出现的时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_symbol', name='uq_market_instrument_normalized_symbol'),
    sa.UniqueConstraint('provider', 'normalized_provider_symbol', name='uq_market_instrument_provider_symbol')
    )
    op.create_index(op.f('ix_market_instrument_id'), 'market_instrument', ['id'], unique=False)
    op.create_index('ix_market_instrument_is_hot_active', 'market_instrument', ['is_hot', 'is_active'], unique=False)
    op.create_index('ix_market_instrument_name', 'market_instrument', ['name'], unique=False)
    op.create_index(op.f('ix_market_instrument_normalized_provider_symbol'), 'market_instrument', ['normalized_provider_symbol'], unique=False)
    op.create_index(op.f('ix_market_instrument_normalized_symbol'), 'market_instrument', ['normalized_symbol'], unique=False)
    op.create_index('ix_market_instrument_provider_market_asset_active', 'market_instrument', ['provider', 'market', 'asset_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_market_instrument_symbol'), 'market_instrument', ['symbol'], unique=False)
    op.create_table('market_bar_sync_state',
    sa.Column('instrument_id', sa.Integer(), nullable=False, comment='关联主标的 ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='数据供应商'),
    sa.Column('interval', sa.String(length=16), nullable=False, comment='同步周期'),
    sa.Column('price_type', sa.String(length=16), nullable=False, comment='价格类型'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用同步'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='调度优先级，越小越优先'),
    sa.Column('target_history_bars', sa.Integer(), nullable=True, comment='目标回补 K 线数量'),
    sa.Column('sync_mode', sa.String(length=16), nullable=False, comment='同步模式，如 BACKFILL 或 INCREMENTAL'),
    sa.Column('earliest_synced_bar_time', sa.DateTime(timezone=True), nullable=True, comment='已同步最早 K 线时间'),
    sa.Column('latest_synced_bar_time', sa.DateTime(timezone=True), nullable=True, comment='已同步最新 K 线时间'),
    sa.Column('last_requested_start_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次请求的开始时间'),
    sa.Column('last_requested_end_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次请求的结束时间'),
    sa.Column('next_sync_from', sa.DateTime(timezone=True), nullable=True, comment='下次同步起点'),
    sa.Column('backfill_completed', sa.Boolean(), nullable=False, comment='历史回补是否完成'),
    sa.Column('last_status', sa.String(length=20), nullable=False, comment='最近一次同步状态'),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次尝试同步时间'),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次同步成功时间'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='连续重试次数'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='最近一次错误信息'),
    sa.Column('meta', sa.JSON(), nullable=True, comment='同步上下文和诊断信息'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['market_instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'interval', 'price_type', name='uq_market_bar_sync_state_instrument_interval_price')
    )
    op.create_index('ix_market_bar_sync_state_enabled_priority', 'market_bar_sync_state', ['enabled', 'priority'], unique=False)
    op.create_index(op.f('ix_market_bar_sync_state_id'), 'market_bar_sync_state', ['id'], unique=False)
    op.create_index('ix_market_bar_sync_state_next_sync_from', 'market_bar_sync_state', ['next_sync_from'], unique=False)
    op.create_index('ix_market_bar_sync_state_status_attempt', 'market_bar_sync_state', ['last_status', 'last_attempt_at'], unique=False)
    op.create_table('market_instrument_alias',
    sa.Column('instrument_id', sa.Integer(), nullable=False, comment='关联主标的 ID'),
    sa.Column('alias', sa.String(length=128), nullable=False, comment='原始别名'),
    sa.Column('normalized_alias', sa.String(length=128), nullable=False, comment='归一化后的别名'),
    sa.Column('alias_type', sa.String(length=32), nullable=False, comment='别名类型，如 LEGACY、MANUAL、SEARCH'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='冲突时优先级，越小越优先'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['market_instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias', name='uq_market_instrument_alias_normalized_alias')
    )
    op.create_index(op.f('ix_market_instrument_alias_id'), 'market_instrument_alias', ['id'], unique=False)
    op.create_index('ix_market_instrument_alias_instrument_id', 'market_instrument_alias', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_market_instrument_alias_normalized_alias'), 'market_instrument_alias', ['normalized_alias'], unique=False)
    op.create_index('ix_market_instrument_alias_priority_active', 'market_instrument_alias', ['priority', 'is_active'], unique=False)
    op.create_table('market_ohlcv_bar',
    sa.Column('instrument_id', sa.Integer(), nullable=False, comment='关联主标的 ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='数据供应商'),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False, comment='抓取时使用的 provider symbol'),
    sa.Column('interval', sa.String(length=16), nullable=False, comment='K 线周期，如 1day、1h'),
    sa.Column('price_type', sa.String(length=16), nullable=False, comment='价格类型，如 mid、bid、ask'),
    sa.Column('data_origin', sa.String(length=16), nullable=False, comment='数据来源，如 PROVIDER 或 AGGREGATED'),
    sa.Column('source_interval', sa.String(length=16), nullable=True, comment='若为聚合数据，则记录来源周期'),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False, comment='K 线起始时间，统一存 UTC'),
    sa.Column('open', sa.Numeric(precision=20, scale=10), nullable=False, comment='开盘价'),
    sa.Column('high', sa.Numeric(precision=20, scale=10), nullable=False, comment='最高价'),
    sa.Column('low', sa.Numeric(precision=20, scale=10), nullable=False, comment='最低价'),
    sa.Column('close', sa.Numeric(precision=20, scale=10), nullable=False, comment='收盘价'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='成交量'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['market_instrument.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'interval', 'price_type', 'bar_time', name='uq_market_ohlcv_bar_instrument_interval_price_time')
    )
    op.create_index(op.f('ix_market_ohlcv_bar_id'), 'market_ohlcv_bar', ['id'], unique=False)
    op.create_index('ix_market_ohlcv_bar_instrument_interval_time', 'market_ohlcv_bar', ['instrument_id', 'interval', 'bar_time'], unique=False)
    op.create_index('ix_market_ohlcv_bar_interval_time', 'market_ohlcv_bar', ['interval', 'bar_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_ohlcv_bar_interval_time', table_name='market_ohlcv_bar')
    op.drop_index('ix_market_ohlcv_bar_instrument_interval_time', table_name='market_ohlcv_bar')
    op.drop_index(op.f('ix_market_ohlcv_bar_id'), table_name='market_ohlcv_bar')
    op.drop_table('market_ohlcv_bar')
    op.drop_index('ix_market_instrument_alias_priority_active', table_name='market_instrument_alias')
    op.drop_index(op.f('ix_market_instrument_alias_normalized_alias'), table_name='market_instrument_alias')
    op.drop_index('ix_market_instrument_alias_instrument_id', table_name='market_instrument_alias')
    op.drop_index(op.f('ix_market_instrument_alias_id'), table_name='market_instrument_alias')
    op.drop_table('market_instrument_alias')
    op.drop_index('ix_market_bar_sync_state_status_attempt', table_name='market_bar_sync_state')
    op.drop_index('ix_market_bar_sync_state_next_sync_from', table_name='market_bar_sync_state')
    op.drop_index(op.f('ix_market_bar_sync_state_id'), table_name='market_bar_sync_state')
    op.drop_index('ix_market_bar_sync_state_enabled_priority', table_name='market_bar_sync_state')
    op.drop_table('market_bar_sync_state')
    op.drop_index(op.f('ix_market_instrument_symbol'), table_name='market_instrument')
    op.drop_index('ix_market_instrument_provider_market_asset_active', table_name='market_instrument')
    op.drop_index(op.f('ix_market_instrument_normalized_symbol'), table_name='market_instrument')
    op.drop_index(op.f('ix_market_instrument_normalized_provider_symbol'), table_name='market_instrument')
    op.drop_index('ix_market_instrument_name', table_name='market_instrument')
    op.drop_index('ix_market_instrument_is_hot_active', table_name='market_instrument')
    op.drop_index(op.f('ix_market_instrument_id'), table_name='market_instrument')
    op.drop_table('market_instrument')
    # ### end Alembic commands ###
