"""add user_credit_log table

Revision ID: 2e73255064d3
Revises: 30bd555b50da
Create Date: 2026-03-29 20:46:17.362916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e73255064d3'
down_revision: Union[str, Sequence[str], None] = '30bd555b50da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credit_log',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='关联用户 ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='变动额度（正数代表增加，负数代表消耗，如 -5）'),
    sa.Column('credit_type', sa.Enum('FREE', 'PAID', name='credittype'), nullable=False, comment='消耗的是哪种点数：FREE 还是 PAID'),
    sa.Column('action_type', sa.Enum('SIGNUP_BONUS', 'DAILY_REFILL', 'USE_FLASH_MODEL', 'USE_PRO_MODEL', 'USE_VISION_DIFF', 'TOP_UP', name='actiontype'), nullable=False, comment='动作类型：SIGNUP_BONUS, DAILY_REFILL, USE_FLASH_MODEL, USE_PRO_MODEL, USE_VISION_DIFF, TOP_UP (充值)'),
    sa.Column('balance_after', sa.Integer(), nullable=False, comment='变动后的钱包总余额（免费+付费），用于快速核对账目防篡改'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credit_log_id'), 'user_credit_log', ['id'], unique=False)
    op.create_index(op.f('ix_user_credit_log_user_id'), 'user_credit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credit_log_user_id'), table_name='user_credit_log')
    op.drop_index(op.f('ix_user_credit_log_id'), table_name='user_credit_log')
    op.drop_table('user_credit_log')
    # ### end Alembic commands ###
