"""add user_credit table

Revision ID: 30bd555b50da
Revises: 72b1a6d9faba
Create Date: 2026-03-29 19:16:58.396288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bd555b50da'
down_revision: Union[str, Sequence[str], None] = '72b1a6d9faba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credit',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户'),
    sa.Column('free_credits', sa.Integer(), nullable=False, comment='免费点数（比如每日重置的额度，或一次性赠送额度）'),
    sa.Column('paid_credits', sa.Integer(), nullable=False, comment='付费点数（用户真金白银买的，永不过期）'),
    sa.Column('last_reset_date', sa.Date(), nullable=True, comment='记录上次重置免费点数的日期'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credit_id'), 'user_credit', ['id'], unique=False)
    op.create_index(op.f('ix_user_credit_user_id'), 'user_credit', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credit_user_id'), table_name='user_credit')
    op.drop_index(op.f('ix_user_credit_id'), table_name='user_credit')
    op.drop_table('user_credit')
    # ### end Alembic commands ###
