"""update

Revision ID: 58707b45825a
Revises: 8ef626ad1156
Create Date: 2026-03-30 22:25:33.880072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58707b45825a'
down_revision: Union[str, Sequence[str], None] = '8ef626ad1156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_task',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='对外暴露的唯一任务ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='关联用户 ID'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型，例如：SHL_ANALYZE, CODE_VERIFY'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False, comment='任务当前状态'),
    sa.Column('result', sa.JSON(), nullable=True, comment='任务成功时的返回结果（存放结构化的 JSON 数据）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='任务失败时的错误信息（用于排错）'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_task_id'), 'ai_task', ['id'], unique=False)
    op.create_index(op.f('ix_ai_task_status'), 'ai_task', ['status'], unique=False)
    op.create_index(op.f('ix_ai_task_task_id'), 'ai_task', ['task_id'], unique=True)
    op.create_index(op.f('ix_ai_task_user_id'), 'ai_task', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_task_user_id'), table_name='ai_task')
    op.drop_index(op.f('ix_ai_task_task_id'), table_name='ai_task')
    op.drop_index(op.f('ix_ai_task_status'), table_name='ai_task')
    op.drop_index(op.f('ix_ai_task_id'), table_name='ai_task')
    op.drop_table('ai_task')
    # ### end Alembic commands ###
