"""add is_readed field

Revision ID: af0c96dc672c
Revises: 58707b45825a
Create Date: 2026-03-31 04:54:31.533460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0c96dc672c'
down_revision: Union[str, Sequence[str], None] = '58707b45825a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shl_solver_history', sa.Column('is_readed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shl_solver_history', 'is_readed')
    # ### end Alembic commands ###
