"""add_fields_to_token_record

Revision ID: b6bd61c5f2e3
Revises: 521200355f5e
Create Date: 2026-03-03 12:08:28.244574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bd61c5f2e3'
down_revision: Union[str, Sequence[str], None] = '521200355f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_record', sa.Column('request_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_record', 'request_path')
    # ### end Alembic commands ###
