"""add field cost in llms table

Revision ID: e5c1ecd3cd42
Revises: 2e73255064d3
Create Date: 2026-03-30 02:09:02.335602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c1ecd3cd42'
down_revision: Union[str, Sequence[str], None] = '2e73255064d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms', sa.Column('cost', sa.Integer(), nullable=True, comment='每次调用的成本，单位是算力点数（credits），可以根据实际情况调整为更精细的计费方式'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llms', 'cost')
    # ### end Alembic commands ###
